os: linux
language: node_js
jobs:
  include:
    - stage: install
      script: npm install
      skip_cleanup: true
    - stage: build
      script: npm run build
      skip_cleanup: true
    - stage: test
      script: npm run test
      skip_cleanup: true
    - stage: publish
      script: npx semantic-release
