os: linux
language: node_js
before_script:
  - npm run modules-audit:create
  - npm run modules-audit:process
script:
  - npm run build
  - npm run test
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
