# We use travis workspaces to store artifacts over stages. This feature
# is in Beta as of March 2020. Keep an eye on it!
# https://docs.travis-ci.com/user/using-workspaces/

os: linux
language: node_js

jobs:
  include:

    - stage: build and deploy packages
      script:
        - npm run build:stencil
        - npm run test
      workspaces:
        create:
          name: test-workspace
          paths:
            - dist
            - loader
            - .stencil
            - node_modules
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

    - stage: build and deploy storybook
      install: skip
      workspaces:
        use: test-workspace
      script:
        - npm install netlify-cli -g
        - npm run build:storybook
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - netlify deploy --prod --message "Here we write the current version" --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./storybook-static/
