os: linux
language: node_js
# cache:
#   directories:
#   - node_modules
jobs:
  include:
    - stage: build and publish
      script:
        - npm run build
        - npm run test
      after_success:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - npm publish
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
