os: linux
language: node_js
jobs:
  include:
    - stage: install
      script: npm install
      cleanup: false
    - stage: build
      script: npm run build
      cleanup: false
    - stage: test
      script: npm run test
      cleanup: false
    - stage: publish
      script: npx semantic-release
