language: node_js
cache:
  directories:
  - node_modules
before_install:
  - echo "1. BEFORE INSTALL"
before_script:
  - echo "2. BEFORE SCRIPT"
script:
  - echo "3. SCRIPT"
  - npm run build
after_failure:
  - echo "4. AFTER FAILURE"
after_success:
  - echo "4. AFTER SUCCESS"
before_deploy:
  - echo "5. BEFORE DEPLOY"
deploy:
  - echo "6. DEPLOY"
  - echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
  - npm publish
after_deploy:
  - echo "7. AFTER DEPLOY"
after_script:
  - echo "8. AFTER SCRIPT"
