language: node_js
cache:
  directories:
  - node_modules
before_script:
  - echo "WILL BUILD"
script:
  - npm run build
after_success:
  - echo '//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}' > .npmrc
  - npm publish
