# We use travis worksapces to store artifacts over stages. This feature
# is in Beta as of March 2020. Keep an eye on it!
# https://docs.travis-ci.com/user/using-workspaces/

os: linux
language: node_js

jobs:
  include:

    - stage: build and deploy packages
      script:
        - npm run build:stencil
        - npm run test
      workspaces:
        name: default-workspace
        paths:
          - /dist
          - /loader
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

    - stage: build and deploy storybook
      workspaces:
        use: default-workspace
      install: skip
      script:
        - node --version
        - npm install netlify-cli -g
        - npm run build:storybook
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - netlify deploy --prod --message "Here we write the current version" --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./storybook-static/
