os: linux
language: node_js

jobs:
  include:

    - stage: build and deploy packages
      script:
        - npm run build:stencil
        - npm run test
      workspaces:
        name: default-workspace
        paths:
          - /
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

    - stage: build and deploy storybook
      workspaces:
        use: default-workspace
      script:
        - npm install netlify-cli -g
        - npm run build:storybook
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - netlify deploy --prod --message "Here we write the current version" --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./storybook-static/

# https://docs.travis-ci.com/user/using-workspaces/
