os: linux
language: node_js
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run test
deploy:
  provider: script
  cleanup: false
  skip_cleanup: true
  script: npx semantic-release
