# Add release version as message to netlify deployment
# 1. .releaserc -> write version to .version
# 2. add --message in format: ::VERSION:: in netlify deploy

# Initially, we used travis stages and workspaces
# https://docs.travis-ci.com/user/using-workspaces/
# with stage1: build and deploy to npm
# stage2: build storybook and deploy to netlify
# Where stage2 takes up to 2 minutes.
# The problem: if no new version is released, it is not possible to define
# a condition so that stage2 is not run. Therefore the build would last 2 min
# longer than neccessary.
# Solution: For simplicity, we ommit stages and do everything in the script
# block of one job.

os: linux
language: node_js

jobs:
  include:
    - stage: build, test and deploy packages and storybook
      script:

        # make stnecil production build
        - npm run build:stencil

        # run tests
        - npm run test

        # run semantic release
        - npx semantic-release

        # build storybook and run netlify deploy
        - ./ci/netlify_deploy.sh

        # add DEPLOYMENTS.md
        - test -f .version && node ./ci/build_release_urls.js --netlifyToken=$NETLIFY_AUTH_TOKEN --netlifySiteId=$NETLIFY_SITE_ID --gitUser=lyne-admin --gitToken=$GH_PERSONAL_TOKEN --gitMail=$GH_MAIL && git push -u origin master
