# We use travis workspaces to store artifacts over stages. This feature
# is in Beta as of March 2020. Keep an eye on it!
# https://docs.travis-ci.com/user/using-workspaces/

# Add release version as message to netlify deployment
# 1. .releaserc -> write version to .version
# 2. add --message in format: ::VERSION:: in netlify deploy

os: linux
language: node_js

jobs:
  include:

    - stage: build, test and deploy packages
      script:
        - npm run build:stencil
        - npm run test
      workspaces:
        create:
          name: build-workspace
          paths:
            - dist
            - loader
            - .stencil
            - node_modules
            - .version.js
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

    - stage: build and deploy storybook
      install: skip
      workspaces:
        use: build-workspace
      script:
        - npm install netlify-cli -g
        - npm run build:storybook
      deploy:
        provider: script
        skip_cleanup: true
        script: test -f .version.js && netlify deploy --prod --message "::`cat .version.js`::" --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir ./storybook-static/
