os: linux
language: node_js
# cache:
#   directories:
#   - node_modules
jobs:
  include:
    - stage: build
    - script: npm run build
    - stage: test
    - script: npm run test
    - stage: publish
    - script:
      - echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
      - npm publish
