# Add release version as message to Netlify deployment
# 1. .releaserc -> write version to .version
# 2. add --message in format: ::VERSION:: in netlify deploy

# Initially, we used Travis's stages and workspaces
# https://docs.travis-ci.com/user/using-workspaces/
# In stage1: Build and deploy to npm
# In stage2: Build Storybook and deploy to Netlify
# Where stage2 takes up to 2 minutes.
# The problem: If no new version is released, it is not possible to define
# a condition so that stage2 is not run. Therefore the build would last 2 min
# longer than necessary.
# Solution: For simplicity, we omit stages and do everything in the script
# block of one job.

os: linux
language: node_js
script:
  - rm -rf node_modules
  - npm cache clean --force
  - npm run build
  - npm run chromatic
