[[build]]
  base = "/"
  publish = "/"
  command = [
    "echo 'THIS WILL BE EXECUTED AS WELL'",
    "npm run build && echo '//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}' > .npmrc && npm publish"
  ]
